<?php if ($_item = $this->getItem()): ?>
<div class="item-info">
    <a href="<?php echo $_item->getProductUrl() ?>" class="product-image"><img src="<?php echo  $_item->getImageUrl() ?>" width="100" height="100" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>" /></a>
    <div class="product-details">
        <h3 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></h3>
        <div class="price-box">
            <span class="regular-price">
                <span class="price"><?php echo Mage::helper('core')->currency($_item->getSpecialPrice() ? $_item->getSpecialPrice() : $_item->getPrice(), true, false) ?></span>
            </span>
        </div>
    </div>
</div>
<?php endif;?>