<?php if ($this->hasItems()): ?>
<div id="ordergroove-widget">
    <div class="widget-box">
        <div class="box-title">
            <h2><?php echo $this->getTitle() ?></h2>
        </div>
        <?php $i=0; foreach ($this->getItemCollection() as $_item): ?>
            <?php if ($i++ % $this->getColumnCount() == 0): ?>
                <ul class="widget-grid">
            <?php endif ?>
                    <li class="item<?php if (($i - 1) % $this->getColumnCount() == 0):?> first<?php elseif ($i % $this->getColumnCount() == 0):?> last<?php endif;?>">
                        <?php
                           $itemBlock = $this->getChild('widget.u2p.item')->setItem($_item)->setPosition($i);
                           echo $itemBlock->toHtml();
                        ?>
                    </li>
            <?php if ($i % $this->getColumnCount() == 0 || $i == $this->getItemsCount()): ?>
                </ul>
            <?php endif ?>
        <?php endforeach; ?>
    </div>
</div>
<?php endif ?>